### PR TITLE
incorporate method dispatch for sf

### PR DESCRIPTION
**Pull request by mhweber**
Is it really this simple or did I miss something?

### CODE REVIEW

**Comment by fawda123** [comment]
@mhweber I think it's close.  The checks passed but for some reason the warnings under the RCMD package checks didn't register as failed checks.  This is probably something in the check settings I did a while back, not sure why.  

But, in short, I think we need to add sf to the depends field in the DESCRIPTION file and rerun `devtools::document()`.  That should make the warnings go away in the package check:

https://github.com/USEPA/micromap/pull/52/checks?check_run_id=2823625772

If you want to merge the PR, I can sync it with my fork, make the changes and submit a PR here.

**Comment by mhweber** [comment]
@fawda123 - makes sense.  I made those changes and I think it's good to go now, but I'll hold off merging this PR until I hear from you.

**Comment by fawda123** [comment]
@mhweber I don't think I can sync it with my fork until you merge the PR.  Can you do that please?

**Comment by mhweber** [comment]
Merged - I'll delete branch shortly but leave for now

**Pull request merged**
